### ISSUE TITLE
[Export] Attempting to export A0 landscape

### ISSUE THREAD

**Issue by Heatdh** [itailang/poster_guide#1]
I encountered an issue while trying to export a poster to A0 size after editing and selecting the appropriate dimensions. For some reason, the exported size does not match the specified dimensions. 

Do you have any suggestions on how to address this issue? It seems to be related to Drawio rather than the template itself.

**How to reproduce the issue:** Select the diagram, group it, fit it to A0, and then export. After exporting, open the file in Adobe Reader and press Ctrl + D to check the dimensions.

Thank you in advance

**Comment by itailang** [comment]
@Heatdh,

Thanks for your inquiry. When exporting to pdf (File --> Export as --> PDF...), the default setting is to add a border. To avoid it, you should set `Border Width` to 0 (see the attached image). I also recommend unchecking the box `Include a copy of my diagram`. 

![image](https://github.com/user-attachments/assets/492c7519-d7a7-4c86-926c-cf5e9690ce02)

Please let me know if you have any further questions.

Thanks!
